version: 2.1
jobs:
  node:
    working_directory: ~/rnDeploy
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/rnDeploy
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  create_keystore_properties: &create_keystore_properties
    run:
      name: Create keystore.properties
      command: printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=%s\nreleaseStorePassword=%s' \
        $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_KEYSTORE $RELEASE_STORE_PASSWORD > keystore.properties

  decode_android_key: &decode_android_key
    run:
      name: Decode Android key store
      command: echo $KEYSTORE | base64 -d | tee keystore app/keystore > /dev/null

  android-build-and-test:
    working_directory: ~/rnDeploy/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/rnDeploy

      - attach_workspace:
          at: ~/rnDeploy
      - *create_keystore_properties
      - *decode_android_key

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane deploy
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane dev flavor:alpha branch:${CIRCLE_BRANCH} app_id:FIREBASE_APP_ID firebase_token:$FIREBASE_TOKEN

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
