# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
     before_all do
        setup_circle_ci
      end

     desc "Runs all the tests"
       lane :test do
         scan
       end

        desc "Ad-hoc build"
         lane :adhoc do
           match(type: "adhoc")
           gym(export_method: "ad-hoc")
         end

          desc "Deploy to Firebase internal developer group"
                lane :dev do
                    adhoc
                    firebase_app_distribution(
                        app: "1:1079470051825:ios:9e22ac3e4ba5858fc8b450",
                        "groups": "test",
                        release_notes: "test",
                    )
                end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
