# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Add env variables"
    lane :write_to_env do |options|
         File.open("../../.env","a") do |f|
           options.each do |key, value|
             f.puts "#{key}=\"#{value}\""
           end
         end
     end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end

   lane :adhoc_staging do |options|
      write_to_env options
      match(type: "adhoc")
      gym(export_method: "ad-hoc")
    end


  desc "Deploy to Firebase internal tester group"
  lane :dev do |options|
    adhoc
    commit = last_git_commit
    commit_notes = commit[:message]
    publish_to_firebase(
        branch: options[:branch],
        groups: options[:groups],
        notes: commit_notes,
        author: commit[:author],
        app_id: options[:app_id],
        firebase_token: options[:firebase_token]
    )
  end

  lane :staging do |options|
      env_variables = {}
      env_variables[:MY_VARIABLE] = options[:my_variable]
      adhoc_staging env_variables
      commit = last_git_commit
      commit_notes = commit[:message]
      publish_to_firebase(
          branch: options[:branch],
          groups: options[:groups],
          notes: commit_notes,
          author: commit[:author],
          app_id: options[:app_id],
          firebase_token: options[:firebase_token]
      )
    end

  desc "Deploy to Firebase"
  lane :publish_to_firebase do |options|
    build_notes = "Branch: #{options[:branch]}. Built by #{options[:author]}.\n Notes: #{options[:notes]}"
    firebase_app_distribution(
        app: "#{options[:app_id]}",
        groups: "#{options[:groups]}",
        release_notes: build_notes,
        firebase_cli_token: "#{options[:firebase_token]}"
    )
  end
end
