# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build application release"
  lane :build do
    gradle(task: 'clean')
    gradle(task: "assemble", build_type: "Release")
  end

  desc "Deploy to Firebase internal developer group"
  lane :dev do |options|
    build
    commit = last_git_commit
    commit_notes = commit[:message]
    publish_to_firebase(
        flavor: options[:flavor],
        branch: options[:branch],
        apk_path: "app/build/outputs/apk/release/app-release.apk",
        groups: options[:groups],
        notes: commit_notes,
        author: commit[:author],
        app_id: options[:app_id],
        firebase_token: options[:firebase_token]
    )
  end

  desc "Deploy to Firebase"
  lane :publish_to_firebase do |options|
    build_notes = "Branch: #{options[:branch]}.  Built by #{options[:author]}"
    firebase_app_distribution(
        app: "#{options[:app_id]}",
        groups: options[:groups],
        release_notes: build_notes,
        apk_path: "app/build/outputs/apk/release/app-release.apk",
        firebase_cli_token: "#{options[:firebase_token]}"
    )
  end
end
